export const commonUsagesMap: Record<string, string> = {
  "Eco-friendly packaging": "/Assets/AboutEcoTile2.webp",
  "Product branding": "/Assets/commonusage1.webp",
  "Personalized gift packaging": "/Assets/commonusage1.webp",
  "Event packaging": "/Assets/commonusage1.webp",
  "Retail packaging": "/Assets/commonusage1.webp",
  "Storing food items": "/Assets/commonusage1.webp",
  "Storing medical supplies": "/Assets/commonusage1.webp",
  "Organizing domestic items": "/Assets/commonusage1.webp",
  "Organizing industrial items": "/Assets/commonusage1.webp",
  "Packaging loose-leaf tea and herbs": "/Assets/commonusage1.webp",
  "Food processing": "/Assets/commonusage1.webp",
  "Export industries": "/Assets/commonusage1.webp",
  "Shipping documents": "/Assets/commonusage1.webp",
  "Packaging clothing": "/Assets/commonusage1.webp",
  "Packaging lightweight parcels": "/Assets/commonusage1.webp",
  "E-commerce packaging": "/Assets/commonusage1.webp",
  "Postal services": "/Assets/commonusage1.webp",
  "Logistics operations": "/Assets/commonusage1.webp",
  "Bakery packaging": "/Assets/commonusage1.webp",
  "Grocery packaging": "/Assets/commonusage1.webp",
  "Café takeaway packaging": "/Assets/commonusage1.webp",
  "Household waste collection": "/Assets/commonusage1.webp",
  "Commercial waste collection": "/Assets/commonusage1.webp",
  "Industrial waste disposal": "/Assets/commonusage1.webp",
  "Garment packing": "/Assets/commonusage1.webp",
  "General-purpose storage": "/Assets/commonusage1.webp",
  "Boutique retail packaging": "/Assets/commonusage1.webp",
  "Supermarket packaging": "/Assets/commonusage1.webp",
  "Electronics packaging": "/Assets/commonusage1.webp",
  "Fragile item shipping": "/Assets/commonusage1.webp",
  "Warehousing": "/Assets/commonusage1.webp",
  "Pallet wrapping": "/Assets/commonusage1.webp",
  "Product bundling": "/Assets/commonusage1.webp",
  "Goods securing during transport": "/Assets/commonusage1.webp",
  "Food wrapping and preservation": "/Assets/commonusage1.webp",
  "Carrying purchased goods": "/Assets/commonusage1.webp",
  "Carrying household essentials": "/Assets/commonusage1.webp",
  "Office packaging tasks": "/Assets/commonusage1.webp",
  "Industrial packaging applications": "/Assets/commonusage1.webp",
  "Painting tasks": "/Assets/commonusage1.webp",
  "Crafting applications": "/Assets/commonusage1.webp",
  "Labeling": "/Assets/commonusage1.webp",
  "Light-duty bundling": "/Assets/commonusage1.webp",
  "Mounting applications": "/Assets/commonusage1.webp",
  "Signage work": "/Assets/commonusage1.webp",
  "Surface bonding": "/Assets/commonusage1.webp",
  "Beverage serving (hot and cold drinks)": "/Assets/commonusage1.webp",
  "Dairy packaging": "/Assets/commonusage1.webp",
  "Dessert presentation": "/Assets/commonusage1.webp",
  "Food delivery packaging": "/Assets/commonusage1.webp",
  "Sauce and condiment serving": "/Assets/commonusage1.webp",
  "Ice cream and yogurt packaging": "/Assets/commonusage1.webp",
  "Semi-liquid food packaging": "/Assets/commonusage1.webp",
  "Food display and storage": "/Assets/commonusage1.webp",
  "Ready-to-eat food packaging": "/Assets/commonusage1.webp",
  "Catering services": "/Assets/commonusage1.webp",
  "Party food service": "/Assets/commonusage1.webp",
  "Household food service": "/Assets/commonusage1.webp",
  "Food storage": "/Assets/commonusage1.webp",
  "Household organization": "/Assets/commonusage1.webp",
  "General shipping applications": "/Assets/commonusage1.webp",
  "Construction applications": "/Assets/commonusage1.webp",
  "Automotive applications": "/Assets/commonusage1.webp",
  "Manufacturing applications": "/Assets/commonusage1.webp",
  "Dining table protection": "/Assets/commonusage1.webp",
  "Decorative table setups": "/Assets/commonusage1.webp",
  "Industrial goods packaging": "/Assets/commonusage1.webp",
  "Airtight food storage": "/Assets/commonusage1.webp",
  "Vacuum packaging": "/Assets/commonusage1.webp",
  "Package securing": "/Assets/commonusage1.webp",
  "Large shipment handling": "/Assets/commonusage1.webp",
  "Interior decoration": "/Assets/commonusage1.webp",
  "Agricultural cultivation": "/Assets/commonusage1.webp",
  "Plant growing": "/Assets/commonusage1.webp",
  "Crop production": "/Assets/commonusage1.webp",
  "Item bundling": "/Assets/commonusage1.webp",
  "Item securing": "/Assets/commonusage1.webp",
  "Sports applications": "/Assets/commonusage1.webp",
  "Gardening": "/Assets/commonusage1.webp",
  "Horticulture": "/Assets/commonusage1.webp",
  "Farming applications": "/Assets/commonusage1.webp",
  "Plastic product manufacturing": "/Assets/commonusage1.webp",
  "Packaging material production": "/Assets/commonusage1.webp",
  "Pharmaceutical packaging": "/Assets/commonusage1.webp",
  "Tamper-evident sealing": "/Assets/commonusage1.webp",
  "Heat sealing applications": "/Assets/commonusage1.webp",
  "Electrical sealing applications": "/Assets/commonusage1.webp",
  "Plastic coloring and modification": "/Assets/commonusage1.webp",
  "Container manufacturing": "/Assets/commonusage1.webp",
  "Film production": "/Assets/commonusage1.webp",
  "Molded product manufacturing": "/Assets/commonusage1.webp",
  "Weight measurement": "/Assets/commonusage1.webp",
  "Packaging and labeling operations": "/Assets/commonusage1.webp",
  "Heat shrinking": "/Assets/commonusage1.webp",
  "Paint removal": "/Assets/commonusage1.webp",
  "Material drying": "/Assets/commonusage1.webp",
  "Soldering": "/Assets/commonusage1.webp",
  "Material softening": "/Assets/commonusage1.webp",
  "Protective covering": "/Assets/commonusage1.webp",
  "Promotional packaging": "/Assets/commonusage1.webp",
  "Product wrapping": "/Assets/commonusage1.webp",
};