export const commonUsagesMap: Record<string, string> = {
  "Aluminium Box 1": "/Assets/UsageImages/Aluminium Box/Aluminium Box1.webp",
  "Aluminium Box 2": "/Assets/UsageImages/Aluminium Box/Aluminium Box 2.webp",
  "Aluminium Box 3": "/Assets/UsageImages/Aluminium Box/Aluminium Box 3.webp",
  "Aluminium Box 4": "/Assets/UsageImages/Aluminium Box/Aluminium Box 4.webp",
  "Baking Use": "/Assets/UsageImages/Aluminium Box/Baking Use.webp",
  "Delivery Packaging": "/Assets/UsageImages/Aluminium Box/Delivery Packaging.webp",
  "Food Takeaway": "/Assets/UsageImages/Aluminium Box/Food Takeaway.webp",

  "Agriculture  Product Packing": "/Assets/UsageImages/Band Sealer/Agriculture.webp",
  "Food Packaging Use": "/Assets/UsageImages/Band Sealer/Food.webp",
  "Industrial Production Line": "/Assets/UsageImages/Band Sealer/Industrial.webp",

  "Agriculture usage ": "/Assets/UsageImages/Black Polythene/Agriculture.webp",
  "Contractions work ": "/Assets/UsageImages/Black Polythene/Contractions.webp",
  "Shipping Material cover": "/Assets/UsageImages/Black Polythene/Shipping.webp",

  "Eco Retail": "/Assets/UsageImages/Brown Paper Bag/Eco.webp",
  "Gift packing": "/Assets/UsageImages/Brown Paper Bag/Gift.webp",
  "Shopping Use": "/Assets/UsageImages/Brown Paper Bag/Shopping.webp",

  "Packing Process": "/Assets/UsageImages/Bubble Wrapping/Packing.webp",
  "Protection Use": "/Assets/UsageImages/Bubble Wrapping/Protection.webp",
  "Shipping Setup 1": "/Assets/UsageImages/Bubble Wrapping/Shipping (2).webp",
  "Shipping Setup": "/Assets/UsageImages/Bubble Wrapping/Shipping.webp",

  "Calcium Carbonate  1": "/Assets/UsageImages/Calcium Carbonate/Calcium f.webp",
  "Calcium Carbonate  2": "/Assets/UsageImages/Calcium Carbonate/Calcium.webp",
  "Calcium Carbonate 3": "/Assets/UsageImages/Calcium Carbonate/Calcium Carbonate  2.webp",
  "Greater fruition": "/Assets/UsageImages/Calcium Carbonate/Greater.webp",
  "Plant Grawing": "/Assets/UsageImages/Calcium Carbonate/Plant.webp",

  "Artistic Detail": "/Assets/UsageImages/Carpet/Artistic.webp",
  "Event Setup": "/Assets/UsageImages/Carpet/Event.webp",
  "Interior Use": "/Assets/UsageImages/Carpet/Interior.webp",
  "Luxury Interior": "/Assets/UsageImages/Carpet/Luxury.webp",

  "Clear tub 2": "/Assets/UsageImages/Clear Tub/Clear.webp",
  "Food Packaging": "/Assets/UsageImages/Clear Tub/Food.webp",
  "Storage": "/Assets/UsageImages/Clear Tub/Storage.webp",
  "Transparency": "/Assets/UsageImages/Clear Tub/Transparency.webp",

  "Food Wrap": "/Assets/UsageImages/Cling Film/Food.webp",
  "Fresh Storage": "/Assets/UsageImages/Cling Film/Fresh.webp",
  "Kitchen Use": "/Assets/UsageImages/Cling Film/Kitchen.webp",

  "Color Bag 2": "/Assets/UsageImages/Color Bag/Color 2.webp",
  "Color Sorting": "/Assets/UsageImages/Color Bag/Color.webp",
  "Retail ware shopping": "/Assets/UsageImages/Color Bag/Retail.webp",
  "Strong Handle": "/Assets/UsageImages/Color Bag/Strong.webp",

  "Activities and Event Decor": "/Assets/UsageImages/Color Polythene/Activities.webp",
  "Color Coding and Organization": "/Assets/UsageImages/Color Polythene/Color.webp",
  "Gift Wrapping and Aesthetic Packaging": "/Assets/UsageImages/Color Polythene/Gift.webp",

  "Courier bags 1": "/Assets/UsageImages/Courier Bags/Courier.webp",
  "Courier bags 2": "/Assets/UsageImages/Courier Bags/Courier2.webp",
  "Courier bags packaging": "/Assets/UsageImages/Courier Bags/Courier3.webp",
  "Delivery": "/Assets/UsageImages/Courier Bags/CourierPackingBags.webp",
  "E-commerce Shipping": "/Assets/UsageImages/Courier Bags/Delivery.webp",
  "Privacy protection": "/Assets/UsageImages/Courier Bags/E-commerce.webp",
  "Courier bags 3": "/Assets/UsageImages/Courier Bags/Privacy.webp",

  "Cup (130ml)": "/Assets/UsageImages/Cup (130ml)/Cup.webp",
  "Drink serve": "/Assets/UsageImages/Cup (130ml)/Drink.webp",
  "Events ": "/Assets/UsageImages/Cup (130ml)/Events.webp",
  "Takeaways": "/Assets/UsageImages/Cup (130ml)/Takeaways.webp",

  "Decoration Use 2": "/Assets/UsageImages/Double-sided tape/Decoration.webp",
  "Decoration Use": "/Assets/UsageImages/Double-sided tape/Decoration2.webp",
  "Design Work": "/Assets/UsageImages/Double-sided tape/Design.webp",
  "Double-sided tape 1": "/Assets/UsageImages/Double-sided tape/Double-sided.webp",
  "Double-sided tape 2": "/Assets/UsageImages/Double-sided tape/Double-sided2.webp",
  "Mounting Use": "/Assets/UsageImages/Double-sided tape/Mounting.webp",

  "Beverage Serve": "/Assets/UsageImages/Drinking Cup/Beverage.webp",
  "Drinking cup 1": "/Assets/UsageImages/Drinking Cup/Drinking.webp",
  "Drinking cup 4": "/Assets/UsageImages/Drinking Cup/Drinking2.webp",
  "Event Use": "/Assets/UsageImages/Drinking Cup/Event.webp",
  "Takeaway": "/Assets/UsageImages/Drinking Cup/Takeaway.webp",

  "Drinking easily": "/Assets/UsageImages/Drinking Straw/Drinking2.webp",
  "Drinking Straw 2": "/Assets/UsageImages/Drinking Straw/Drinking3.webp",
  "Drinking Straw 3": "/Assets/UsageImages/Drinking Straw/Drinking4.webp",
  "Eco Drink": "/Assets/UsageImages/Drinking Straw/Eco.webp",
  "Good Quality": "/Assets/UsageImages/Drinking Straw/Good.webp",

  "Feature or Temporary Floor Area": "/Assets/UsageImages/Floor Mat/Feature.webp",
  "Instant Floor Makeover": "/Assets/UsageImages/Floor Mat/Instant.webp",
  "Under-Furniture Floor Protection": "/Assets/UsageImages/Floor Mat/Under-Furniture.webp",

  "Cleaning": "/Assets/UsageImages/Garbage Bag/Cleaning.webp",
  "Garbage Bag 2": "/Assets/UsageImages/Garbage Bag/Garbage.webp",
  "Household Use": "/Assets/UsageImages/Garbage Bag/Household.webp",
  "Industrial Use": "/Assets/UsageImages/Garbage Bag/Industrial.webp",

  "Easily Handling": "/Assets/UsageImages/Grosery Bag/Easily.webp",
  "household essentials": "/Assets/UsageImages/Grosery Bag/household.webp",
  "Strong finish.": "/Assets/UsageImages/Grosery Bag/Strong.webp",

  "Agriculture Field": "/Assets/UsageImages/Grow Bag/Agriculture.webp",
  "Close-up Growth": "/Assets/UsageImages/Grow Bag/Close-up.webp",
  "Plant Growing": "/Assets/UsageImages/Grow Bag/Plant.webp",

  "Agriculture": "/Assets/UsageImages/Gypsum/Agriculture.webp",
  "Construction": "/Assets/UsageImages/Gypsum/Construction.webp",
  "Gypsum 1": "/Assets/UsageImages/Gypsum/Gypsum1.webp",
  "Gypsum 2": "/Assets/UsageImages/Gypsum/Gypsum2.webp",
  "Gypsum 3": "/Assets/UsageImages/Gypsum/Gypsum3.webp",
  "Gypsum 4": "/Assets/UsageImages/Gypsum/Gypsum4.webp",
  "Industrial & Specialized Uses": "/Assets/UsageImages/Gypsum/Industrial.webp",

  "Bundling wires with heat shrink": "/Assets/UsageImages/Hot Gun/Bundling_wires_with_heat_shrink_202605041141.webp",
  "Heat Shrink Tubing and Wrapping": "/Assets/UsageImages/Hot Gun/Heat.webp",
  "Paint and Varnish Removal": "/Assets/UsageImages/Hot Gun/Paint.webp",

  "Agriculture use 1": "/Assets/UsageImages/LDPE Polythene/Agriculture.webp",
  "Agriculture use 2": "/Assets/UsageImages/LDPE Polythene/download.webp",
  "Fashon Indruscial Use": "/Assets/UsageImages/LDPE Polythene/Fashon.webp",
  "Food Packaging 2": "/Assets/UsageImages/LDPE Polythene/Food.webp",
  "LDPE Polythene 4": "/Assets/UsageImages/LDPE Polythene/LDPE.webp",

  "Food Safety": "/Assets/UsageImages/Lid/Food.webp",
  "Spill Protection": "/Assets/UsageImages/Lid/Spill.webp",

  "Branding": "/Assets/UsageImages/Lunch Box/Branding.webp",
  "Food Packing": "/Assets/UsageImages/Lunch Box/Food.webp",
  "Lunch Box 3": "/Assets/UsageImages/Lunch Box/Lunch.webp",
  "Lunch Box": "/Assets/UsageImages/Lunch Box/Lunch2.webp",
  "Takeaway 2": "/Assets/UsageImages/Lunch Box/Takeaway.webp",

  "Improves Photosynthesis": "/Assets/UsageImages/Magnesium Sulphate/Improves.webp",
  "Increases crop yields": "/Assets/UsageImages/Magnesium Sulphate/Increases.webp",
  "Magnesium Sulphate 1": "/Assets/UsageImages/Magnesium Sulphate/Magnesium.webp",
  "Magnesium Sulphate 2": "/Assets/UsageImages/Magnesium Sulphate/Magnesium2.webp",
  "Magnesium Sulphate 3": "/Assets/UsageImages/Magnesium Sulphate/Magnesium3.webp",
  "Soil Conditioning": "/Assets/UsageImages/Magnesium Sulphate/Soil.webp",

  "Manufacturing Use": "/Assets/UsageImages/Master Batch/Manufacturing.webp",
  "Material Display": "/Assets/UsageImages/Master Batch/Material.webp",
  "Plastic Coloring": "/Assets/UsageImages/Master Batch/Plastic.webp",
  "To make plastic items": "/Assets/UsageImages/Master Batch/To.webp",

  "Agriculture Setup": "/Assets/UsageImages/Mushroom Grow Bag/Agriculture.webp",
  "Farming Use": "/Assets/UsageImages/Mushroom Grow Bag/Farming.webp",
  "Farming Use 2": "/Assets/UsageImages/Mushroom Grow Bag/Farming2.webp",
  "Growth Stage": "/Assets/UsageImages/Mushroom Grow Bag/Growth.webp",

  "Agriculture Concept 2": "/Assets/UsageImages/Mushroom Seed/Agriculture.webp",
  "Commercial Farming": "/Assets/UsageImages/Mushroom Seed/Commercial.webp",
  "Farming": "/Assets/UsageImages/Mushroom Seed/Farming.webp",

  "Heavy Duty Use": "/Assets/UsageImages/Nylon Rope/Heavy.webp",
  "Nylon Rope 2": "/Assets/UsageImages/Nylon Rope/Nylon.webp",
  "Outdoor Use": "/Assets/UsageImages/Nylon Rope/Outdoor.webp",

  "Events": "/Assets/UsageImages/Paper CUp/Events.webp",
  "Hot Drinks": "/Assets/UsageImages/Paper CUp/Hot.webp",
  "Paper cup 2": "/Assets/UsageImages/Paper CUp/Paper.webp",
  "Takeaway 1": "/Assets/UsageImages/Paper CUp/Takeaway.webp",

  "Disposable Dining": "/Assets/UsageImages/Paper Plate/Disposable.webp",
  "Event Use 2": "/Assets/UsageImages/Paper Plate/Event.webp",
  "Food Serving": "/Assets/UsageImages/Paper Plate/Food.webp",
  "Paper plates 2": "/Assets/UsageImages/Paper Plate/Paper.webp",
  "Paper plates 4": "/Assets/UsageImages/Paper Plate/Paper2.webp",

  "Dining Use": "/Assets/UsageImages/Paper Serviette/Dining.webp",
  "Glass Cleaning": "/Assets/UsageImages/Paper Serviette/Glass.webp",
  "Hygiene": "/Assets/UsageImages/Paper Serviette/Hygiene.webp",
  "Paper Serviette 1": "/Assets/UsageImages/Paper Serviette/Paper.webp",
  "Paper Serviette 2": "/Assets/UsageImages/Paper Serviette/Paper2.webp",

  "Branding 2": "/Assets/UsageImages/Paper tub/Branding.webp",
  "Food Packaging 3": "/Assets/UsageImages/Paper tub/Food.webp",

  "Food Packaging 4": "/Assets/UsageImages/Plastic box/Food.webp",
  "Storage Space": "/Assets/UsageImages/Plastic box/Storage.webp",
  "Transparently": "/Assets/UsageImages/Plastic box/Tracperantly.webp",
  "Transparently 2": "/Assets/UsageImages/Plastic box/Transparently.webp",

  "Aluminium Bag Sealing": "/Assets/UsageImages/Polythene Sealer/Aluminium (1).webp",
  "AluminiumClear Bag Sealing": "/Assets/UsageImages/Polythene Sealer/Clear.webp",
  "Kraft Bag Sealing": "/Assets/UsageImages/Polythene Sealer/Kraft.webp",
  "Polythene Sealer 3": "/Assets/UsageImages/Polythene Sealer/Polythene.webp",

  "Agriculture use": "/Assets/UsageImages/PP Ball/Agriculture.webp",
  "Decorations": "/Assets/UsageImages/PP Ball/Decorations.webp",
  "Plant Growing 2": "/Assets/UsageImages/PP Ball/Plant.webp",

  "Clear Display Packaging": "/Assets/UsageImages/PP Polythene/Clear.webp",
  "Covering Use": "/Assets/UsageImages/PP Polythene/Covering.webp",
  "Laminations": "/Assets/UsageImages/PP Polythene/Laminations.webp",
  "PP Polythene 1": "/Assets/UsageImages/PP Polythene/PP.webp",
  "PP Polythene 2": "/Assets/UsageImages/PP Polythene/PP2.webp",
  "PP Polythene 3": "/Assets/UsageImages/PP Polythene/PP3.webp",

  "Cargo Securing and Tying": "/Assets/UsageImages/PP Rope/Cargo.webp",
  "Construction and Industrial Use": "/Assets/UsageImages/PP Rope/Construction.webp",
  "Marine and Fishing Applications": "/Assets/UsageImages/PP Rope/Marine.webp",

  "Durable, Versatile Materials": "/Assets/UsageImages/PVC Sheet/Durable, Versatile Materials.webp",
  "Outdoor Tent": "/Assets/UsageImages/PVC Sheet/Outdoor Tent.webp",
  "Uses for furniture": "/Assets/UsageImages/PVC Sheet/Uses for furniture.webp",

  "Food Display": "/Assets/UsageImages/PVC Tray/Food.webp",
  "Minimal Space": "/Assets/UsageImages/PVC Tray/Minimal.webp",
  "PVC Tray 1": "/Assets/UsageImages/PVC Tray/PVC.webp",
  "PVC Tray 2": "/Assets/UsageImages/PVC Tray/PVC2.webp",
  "Retail Packaging": "/Assets/UsageImages/PVC Tray/Retail.webp",

  "Food Packing 2": "/Assets/UsageImages/Rubber Band/Food.webp",
  "Office Use": "/Assets/UsageImages/Rubber Band/Office.webp",
  "Packaging Use 2": "/Assets/UsageImages/Rubber Band/Packaging.webp",

  "Diet plan Use": "/Assets/UsageImages/Scale/Diet.webp",
  "Retail Use": "/Assets/UsageImages/Scale/Retail.webp",
  "Scale 1": "/Assets/UsageImages/Scale/Scale.webp",
  "Scale 2": "/Assets/UsageImages/Scale/Scale2.webp",
  "Scale 3": "/Assets/UsageImages/Scale/Scale3.webp",

  "Product Carrying Use": "/Assets/UsageImages/Shoppings Bags/Product.webp",
  "Shopping Bag 2": "/Assets/UsageImages/Shoppings Bags/Shopping.webp",
  "Shopping Bag 3": "/Assets/UsageImages/Shoppings Bags/Shopping2.webp",
  "Strong handle": "/Assets/UsageImages/Shoppings Bags/Strong.webp",
  "Supermarket use": "/Assets/UsageImages/Shoppings Bags/Supermarket.webp",

  "Book Covering": "/Assets/UsageImages/Shrinking Polythene/Book.webp",
  "Packaging Process": "/Assets/UsageImages/Shrinking Polythene/Packaging.webp",
  "Retail Security": "/Assets/UsageImages/Shrinking Polythene/Retail.webp",
  "Shrinking Polythene 1": "/Assets/UsageImages/Shrinking Polythene/Shrinking.webp",

  "Food Serving 3": "/Assets/UsageImages/Source cup/Food.webp",
  "Portion Control": "/Assets/UsageImages/Source cup/Portion.webp",
  "Source cup 1": "/Assets/UsageImages/Source cup/Source.webp",
  "Takeaway Use": "/Assets/UsageImages/Source cup/Takeaway.webp",

  "Gift Packaging": "/Assets/UsageImages/Sticker Bag/Gift.webp",
  "Product Branding 2": "/Assets/UsageImages/Sticker Bag/Product.webp",
  "Retail packaging": "/Assets/UsageImages/Sticker Bag/Retail.webp",

  "Cargo Packaging 1": "/Assets/UsageImages/Strapping Roll/Cargo.webp",
  "Cargo Packaging": "/Assets/UsageImages/Strapping Roll/Cargo2.webp",
  "Heavy Industrial Securing 2": "/Assets/UsageImages/Strapping Roll/Heavy.webp",
  "Machine Strapping Process": "/Assets/UsageImages/Strapping Roll/Machine.webp",

  "Load Securing": "/Assets/UsageImages/Stretch Film 1/Load.webp",
  "Pallet Wrapping": "/Assets/UsageImages/Stretch Film 1/Pallet.webp",
  "Protection Use 1": "/Assets/UsageImages/Stretch Film 1/Protection.webp",

  "Dining Setup": "/Assets/UsageImages/Table Cloth/Dining.webp",
  "Event Decoration": "/Assets/UsageImages/Table Cloth/Event.webp",
  "Home Use": "/Assets/UsageImages/Table Cloth/Home.webp",
  "Table Cloth 1": "/Assets/UsageImages/Table Cloth/Table.webp",
  "Table Cloth 3": "/Assets/UsageImages/Table Cloth/Table2.webp",

  "Design Work 2": "/Assets/UsageImages/Tape/Design.webp",
  "Office Work": "/Assets/UsageImages/Tape/Office.webp",
  "Packaging Use": "/Assets/UsageImages/Tape/Packaging.webp",
  "Painting Work": "/Assets/UsageImages/Tape/Painting.webp",
  "Repair Use": "/Assets/UsageImages/Tape/Repair.webp",

  "Design Work 3": "/Assets/UsageImages/Tape dispenser/Design.webp",
  "Office Use 2": "/Assets/UsageImages/Tape dispenser/Office.webp",
  "Packaging Use 3": "/Assets/UsageImages/Tape dispenser/Packaging.webp",

  "Aluminum ziplock Tea bag 1": "/Assets/UsageImages/Tea Bag/Aluminum.webp",
  "Aroma & Quality Preservation": "/Assets/UsageImages/Tea Bag/Aroma.webp",
  "Product Branding 1": "/Assets/UsageImages/Tea Bag/Product.webp",
  "Product Branding": "/Assets/UsageImages/Tea Bag/Product2.webp",
  "Tea Leaf Packaging": "/Assets/UsageImages/Tea Bag/Tea.webp",

  "Brand Display": "/Assets/UsageImages/Thank You Bag/Brand.webp",
  "Checkout Scene": "/Assets/UsageImages/Thank You Bag/Checkout.webp",
  "Customer Packaging": "/Assets/UsageImages/Thank You Bag/Customer.webp",
  "Thank You Bag 2": "/Assets/UsageImages/Thank You Bag/Thank.webp",

  "Retail Packaging 2": "/Assets/UsageImages/Transparent Box/Retail.webp",
  "Food Display 2": "/Assets/UsageImages/Transparent Box/Food.webp",
  "Storage Use": "/Assets/UsageImages/Transparent Box/Storage.webp",
  "Transparent Box 3": "/Assets/UsageImages/Transparent Box/Transparent.webp",

  "Good Finishing": "/Assets/UsageImages/Tulip Bag/Good.webp",
  "Product Carrying Use 2": "/Assets/UsageImages/Tulip Bag/Product.webp",
  "Retail Shopping Use": "/Assets/UsageImages/Tulip Bag/Retail.webp",
  "Tulip Bag 2": "/Assets/UsageImages/Tulip Bag/Tulip.webp",
  "Tulip Bag 3": "/Assets/UsageImages/Tulip Bag/Tulip2.webp",

  "Agricultural Mulching": "/Assets/UsageImages/U.V Polythene/Agricultural.webp",
  "Greenhouse Protection": "/Assets/UsageImages/U.V Polythene/Greenhouse.webp",
  "Outdoor Material Covering": "/Assets/UsageImages/U.V Polythene/Outdoor.webp",

  "Airtight Compression": "/Assets/UsageImages/Vacuum Bag/Airtight.webp",
  "Durability 2": "/Assets/UsageImages/Vacuum Bag/Durability.webp",
  "Freshness retention": "/Assets/UsageImages/Vacuum Bag/Freshness.webp",
  "Vacuum Bag 1": "/Assets/UsageImages/Vacuum Bag/Vacuum.webp",

  "Diet plan Use 2": "/Assets/UsageImages/Vacuum Machine/Diet.webp",
  "Food Sealing": "/Assets/UsageImages/Vacuum Machine/Food.webp",
  "Kitchen Use 2": "/Assets/UsageImages/Vacuum Machine/Kitchen.webp",
  "Vacuum Machine 3": "/Assets/UsageImages/Vacuum Machine/Vacuum.webp",
  "Vacuum Machine 4": "/Assets/UsageImages/Vacuum Machine/Vacuum2.webp",

  "Food Storage": "/Assets/UsageImages/White Tub/Food.webp",
  "Product Branding 3": "/Assets/UsageImages/White Tub/Product.webp",
  "Takeaway Use 3": "/Assets/UsageImages/White Tub/Takeaway.webp",
  "White tub 1": "/Assets/UsageImages/White Tub/White.webp",
  "White tub 2": "/Assets/UsageImages/White Tub/White2.webp",
  "White tub 3": "/Assets/UsageImages/White Tub/White3.webp",

  "Dessert Preparation Use": "/Assets/UsageImages/Yogurt cup/Dessert.webp",
  "Product Branding 4": "/Assets/UsageImages/Yogurt cup/Product.webp",
  "Product Transparent": "/Assets/UsageImages/Yogurt cup/Product2.webp",

  "Durability and strong": "/Assets/UsageImages/Ziplock Bag/Durability.webp",
  "Food Items": "/Assets/UsageImages/Ziplock Bag/Food.webp",
  "Gift Packing": "/Assets/UsageImages/Ziplock Bag/Gift.webp",
  "Ziplock Bag 1": "/Assets/UsageImages/Ziplock Bag/Ziplock.webp",
  "Ziplock Bag 2": "/Assets/UsageImages/Ziplock Bag/Ziplock2.webp",
  "Ziplock Bag 3": "/Assets/UsageImages/Ziplock Bag/Ziplock3.webp",
  "Ziplock Bag 4": "/Assets/UsageImages/Ziplock Bag/Ziplock4.webp",

  "Coffee, Tea, and Spice Packaging": "/Assets/UsageImages/Ziplock Bag Aluminum/Coffee.webp",
  "Dry Foods and Snacks Preservation": "/Assets/UsageImages/Ziplock Bag Aluminum/Dry.webp",
  "Industrial and Medical Equipment Storage": "/Assets/UsageImages/Ziplock Bag Aluminum/Industrial.webp",

  "Discreet Storage of Valuables": "/Assets/UsageImages/Ziplock Bag Black/Discreet.webp",
  "Professional Industrial Component Sorting": "/Assets/UsageImages/Ziplock Bag Black/Professional.webp",
  "Storing Light-Sensitive Materials": "/Assets/UsageImages/Ziplock Bag Black/Storing.webp",

  "Cosmetic and Natural Skincare Products": "/Assets/UsageImages/Ziplock Bag White/Cosmetic.webp",
  "Organic and Natural Food Packaging": "/Assets/UsageImages/Ziplock Bag White/Organic.webp",
  "Pharmaceutical and Health Products": "/Assets/UsageImages/Ziplock Bag White/Pharmaceutical.webp",

  "Dried Fruits and Nuts Packaging": "/Assets/UsageImages/Ziplock Bag with Window/Dried.webp",
  "Herbal Tea and Floral Blends": "/Assets/UsageImages/Ziplock Bag with Window/Herbal.webp",
  "Premium Pet Treats Packaging": "/Assets/UsageImages/Ziplock Bag with Window/Premium.webp",

  "Coffee, Tea, and Spice Packaging 1": "/Assets/UsageImages/Ziplock bags Color/Coffee.webp",
  "Ziplock bags Color 1": "/Assets/UsageImages/Ziplock bags Color/Ziplock.webp",
  "Ziplock bags Color 2": "/Assets/UsageImages/Ziplock bags Color/Ziplock2.webp",
  "Ziplock bags Color 3": "/Assets/UsageImages/Ziplock bags Color/Ziplock3.webp",
  "Ziplock bags Color 4": "/Assets/UsageImages/Ziplock bags Color/Ziplock4.webp",
  "Ziplock bags Color 5": "/Assets/UsageImages/Ziplock bags Color/Ziplock5.webp",

  "High-end Cosmetic and Fragrance Samples": "/Assets/UsageImages/Ziplock bags Gold/High-end.webp",
  "Luxury Jewelry and Accessory Packaging": "/Assets/UsageImages/Ziplock bags Gold/Luxury.webp",
  "Premium and Luxury Food Packaging": "/Assets/UsageImages/Ziplock bags Gold/Premium.webp",

  "Dry Foods, Snacks, and Treats Packaging": "/Assets/UsageImages/Ziplock bags Kraft Paper/Dry.webp",
  "Organic Tea, Coffee, and Herbal Products Packaging": "/Assets/UsageImages/Ziplock bags Kraft Paper/Organic.webp",
  "Storing Crafts and Small Artisan Items": "/Assets/UsageImages/Ziplock bags Kraft Paper/Storing.webp",

};

export const productUsagesById: Record<number, string[]> = {
  "41": [
    "Aluminium Box 1",
    "Aluminium Box 2",
    "Aluminium Box 3",
    "Aluminium Box 4",
    "Baking Use",
    "Delivery Packaging",
    "Food Takeaway",
  ],
  "63": [
    "Agriculture  Product Packing",
    "Food Packaging Use",
    "Industrial Production Line",
  ],
  "69": [
    "Agriculture usage ",
    "Contractions work ",
    "Shipping Material cover",
  ],
  "12": [
    "Eco Retail",
    "Gift packing",
    "Shopping Use",
  ],
  "18": [
    "Packing Process",
    "Protection Use",
    "Shipping Setup 1",
    "Shipping Setup",
  ],
  "54": [
    "Calcium Carbonate  1",
    "Calcium Carbonate  2",
    "Calcium Carbonate 3",
    "Greater fruition",
    "Plant Grawing",
  ],
  "50": [
    "Artistic Detail",
    "Event Setup",
    "Interior Use",
    "Luxury Interior",
  ],
  "32": [
    "Clear tub 2",
    "Food Packaging",
    "Storage",
    "Transparency",
  ],
  "20": [
    "Food Wrap",
    "Fresh Storage",
    "Kitchen Use",
  ],
  "16": [
    "Color Bag 2",
    "Color Sorting",
    "Retail ware shopping",
    "Strong Handle",
  ],
  "71": [
    "Activities and Event Decor",
    "Color Coding and Organization",
    "Gift Wrapping and Aesthetic Packaging",
  ],
  "11": [
    "Courier bags 1",
    "Courier bags 2",
    "Courier bags packaging",
    "Delivery",
    "E-commerce Shipping",
    "Privacy protection",
    "Courier bags 3",
  ],
  "30": [
    "Cup (130ml)",
    "Drink serve",
    "Events ",
    "Takeaways",
  ],
  "25": [
    "Decoration Use 2",
    "Decoration Use",
    "Design Work",
    "Double-sided tape 1",
    "Double-sided tape 2",
    "Mounting Use",
  ],
  "26": [
    "Beverage Serve",
    "Drinking cup 1",
    "Drinking cup 4",
    "Event Use",
    "Takeaway",
  ],
  "36": [
    "Drinking easily",
    "Drinking Straw 2",
    "Drinking Straw 3",
    "Eco Drink",
    "Good Quality",
  ],
  "51": [
    "Feature or Temporary Floor Area",
    "Instant Floor Makeover",
    "Under-Furniture Floor Protection",
  ],
  "13": [
    "Cleaning",
    "Garbage Bag 2",
    "Household Use",
    "Industrial Use",
  ],
  "22": [
    "Easily Handling",
    "household essentials",
    "Strong finish.",
  ],
  "59": [
    "Agriculture Field",
    "Close-up Growth",
    "Plant Growing",
  ],
  "56": [
    "Agriculture",
    "Construction",
    "Gypsum 1",
    "Gypsum 2",
    "Gypsum 3",
    "Gypsum 4",
    "Industrial & Specialized Uses",
  ],
  "68": [
    "Bundling wires with heat shrink",
    "Heat Shrink Tubing and Wrapping",
    "Paint and Varnish Removal",
  ],
  "61": [
    "Agriculture use 1",
    "Agriculture use 2",
    "Fashon Indruscial Use",
    "Food Packaging 2",
    "LDPE Polythene 4",
  ],
  "34": [
    "Food Safety",
    "Spill Protection",
  ],
  "42": [
    "Branding",
    "Food Packing",
    "Lunch Box 3",
    "Lunch Box",
    "Takeaway 2",
  ],
  "55": [
    "Improves Photosynthesis",
    "Increases crop yields",
    "Magnesium Sulphate 1",
    "Magnesium Sulphate 2",
    "Magnesium Sulphate 3",
    "Soil Conditioning",
  ],
  "65": [
    "Manufacturing Use",
    "Material Display",
    "Plastic Coloring",
    "To make plastic items",
  ],
  "52": [
    "Agriculture Setup",
    "Farming Use",
    "Farming Use 2",
    "Growth Stage",
  ],
  "53": [
    "Agriculture Concept 2",
    "Commercial Farming",
    "Farming",
  ],
  "58": [
    "Heavy Duty Use",
    "Nylon Rope 2",
    "Outdoor Use",
  ],
  "33": [
    "Events",
    "Hot Drinks",
    "Paper cup 2",
    "Takeaway 1",
  ],
  "38": [
    "Disposable Dining",
    "Event Use 2",
    "Food Serving",
    "Paper plates 2",
    "Paper plates 4",
  ],
  "37": [
"Dining Use",
"Glass Cleaning",
"Hygiene",
"Paper Serviette 1",
"Paper Serviette 2",
  ],
  "35": [
"Branding 2",
"Food Packaging 3",
  ],
  "43": [
"Food Packaging 4",
"Storage Space",
"Transparently",
"Transparently 2",
  ],
  "62": [
"Aluminium Bag Sealing",
"AluminiumClear Bag Sealing",
"Kraft Bag Sealing",
"Polythene Sealer 3",
  ],
  "44": [
"Agriculture use",
"Decorations",
"Plant Growing 2",
  ],
  "60": [
"Clear Display Packaging",
"Covering Use",
"Laminations",
"PP Polythene 1",
"PP Polythene 2",
"PP Polythene 3",
  ],
  "45": [
"Durable, Versatile Materials",
"Outdoor Tent",
"Uses for furniture",
  ],
  "39": [
"Food Display",
"Minimal Space",
"PVC Tray 1",
"PVC Tray 2",
"Retail Packaging",
  ],
  "57": [
"Food Packing 2",
"Office Use",
"Packaging Use 2",
  ],
  "66": [
"Diet plan Use",
"Retail Use",
"Scale 1",
"Scale 2",
"Scale 3",
  ],
  "21": [
"Product Carrying Use",
"Shopping Bag 2",
"Shopping Bag 3",
"Strong handle",
"Supermarket use",
  ],
  "47": [
"Book Covering",
"Packaging Process",
"Retail Security",
"Shrinking Polythene 1",
  ],
  "29": [
"Food Serving 3",
"Portion Control",
"Source cup 1",
"Takeaway Use",
  ],
  "1": [
"Gift Packaging",
"Product Branding 2",
"Retail packaging",
  ],
  "49": [
"Cargo Packaging 1",
"Cargo Packaging",
"Heavy Industrial Securing 2",
"Machine Strapping Process",
  ],
  "19": [
"Load Securing",
"Pallet Wrapping",
"Protection Use 1",
  ],
  "46": [
"Dining Setup",
"Event Decoration",
"Home Use",
"Table Cloth 1",
"Table Cloth 3",
  ],
  "23": [
"Design Work 2",
"Office Work",
"Packaging Use",
"Painting Work",
"Repair Use",
  ],
  "67": [
"Design Work 3",
"Office Use 2",
"Packaging Use 3",
  ],
    "9": [
"Aluminum ziplock Tea bag 1",
"Aroma & Quality Preservation",
"Product Branding 1",
"Product Branding",
"Tea Leaf Packaging",
  ],
    "15": [
"Brand Display",
"Checkout Scene",
"Customer Packaging",
"Thank You Bag 2",
  ],
    "40": [
"Retail Packaging 2",
"Food Display 2",
"Storage Use",
"Transparent Box 3",
  ],
    "17": [
"Good Finishing",
"Product Carrying Use 2",
"Retail Shopping Use",
"Tulip Bag 2",
"Tulip Bag 3",
  ],
    "10": [
"Airtight Compression",
"Durability 2",
"Freshness retention",
"Vacuum Bag 1",
  ],
    "48": [
"Diet plan Use 2",
"Food Sealing",
"Kitchen Use 2",
"Vacuum Machine 3",
"Vacuum Machine 4",
  ],
    "31": [
"Food Storage",
"Product Branding 3",
"Takeaway Use 3",
"White tub 1",
"White tub 2",
"White tub 3",
  ],
    "27": [
"Dessert Preparation Use",
"Product Branding 4",
"Product Transparent",
  ],
    "2": [
"Durability and strong",
"Food Items",
"Gift Packing",
"Ziplock Bag 1",
"Ziplock Bag 2",
"Ziplock Bag 3",
"Ziplock Bag 4",
  ],
    "6": [
"Coffee, Tea, and Spice Packaging",
"Dry Foods and Snacks Preservation",
"Industrial and Medical Equipment Storage",
  ],
    "4": [
"Discreet Storage of Valuables",
"Professional Industrial Component Sorting",
"Storing Light-Sensitive Materials",
  ],
    "3": [
"Cosmetic and Natural Skincare Products",
"Organic and Natural Food Packaging",
"Pharmaceutical and Health Products",
  ],
    "5": [
"Coffee, Tea, and Spice Packaging 1",
"Ziplock bags Color 1",
"Ziplock bags Color 2",
"Ziplock bags Color 3",
"Ziplock bags Color 4",
"Ziplock bags Color 5",
  ],
    "7": [
"High-end Cosmetic and Fragrance Samples",
"Luxury Jewelry and Accessory Packaging",
"Premium and Luxury Food Packaging",
  ],
    "8": [
"Dry Foods, Snacks, and Treats Packaging",
"Organic Tea, Coffee, and Herbal Products Packaging",
"Storing Crafts and Small Artisan Items"
  ],



};
