import React from "react";
import SpaIcon from "@mui/icons-material/Spa";
import InventoryIcon from "@mui/icons-material/Inventory";
import HouseIcon from "@mui/icons-material/House";
import LocalShippingIcon from "@mui/icons-material/LocalShipping";
import ShoppingBagIcon from "@mui/icons-material/ShoppingBag";

export const necessaryGoodsIcons: Record<string, React.ReactNode> = {
  "eco-friendly": <SpaIcon />,
  "packaging": <InventoryIcon />,
  "home-use": <HouseIcon />,
  "compostable": <SpaIcon />,
  "waste-management": <LocalShippingIcon />,
  "recyclable": <SpaIcon />,
  "retail": <ShoppingBagIcon />,
  "sustainable": <SpaIcon />,
  "washable": <ShoppingBagIcon />,
  "reusable": <InventoryIcon />,
  "organic": <SpaIcon />,
  "heavy-duty": <LocalShippingIcon />,
  "shipping": <LocalShippingIcon />,
  "protective": <InventoryIcon />,
  "airtight": <InventoryIcon />,
  "kitchenware": <HouseIcon />,
  "plastic-free": <SpaIcon />,
  "natural-fiber": <SpaIcon />,
  "gardening": <SpaIcon />,
  "craft": <InventoryIcon />,
  "versatile": <InventoryIcon />,
  "industrial": <InventoryIcon />,
  "insultated": <InventoryIcon />,
  "BPA-free": <SpaIcon />,
  "durable": <InventoryIcon />,
  "natural-seal": <SpaIcon />,
  "heat-resistant": <InventoryIcon />,
  "breathable": <SpaIcon />,
  "agricultural": <SpaIcon />,
  "cushioning": <InventoryIcon />,
  "space-saving": <InventoryIcon />,
  "plant-based": <SpaIcon />,
  "non-reactive": <SpaIcon />,
  "aesthetic": <SpaIcon />,
  "stackable": <InventoryIcon />,
  "tare-weight-included": <InventoryIcon />,
  "acid-free": <SpaIcon />,
  "soft-touch": <SpaIcon />,
  "vegan-adhesive": <SpaIcon />,
  "printable": <InventoryIcon />,
  "curbside-recyclable": <SpaIcon />,
  "cushioned": <InventoryIcon />,
  "sturdy": <InventoryIcon />,
  "premium-finish": <InventoryIcon />,
  "collapsible": <InventoryIcon />,
  "FSC-certified": <SpaIcon />,
  "ocean-friendly": <SpaIcon />,
  "food-grade": <SpaIcon />,
  "travel-friendly": <LocalShippingIcon />,
  "vegetable-oil-finish": <SpaIcon />,
  "lightweight": <LocalShippingIcon />,
  "heat-insulation": <InventoryIcon />,
  "plant-lined": <SpaIcon />,
  "recycled-plastic": <SpaIcon />,
  "tamper-evident": <InventoryIcon />,
  "strong-adhesive": <InventoryIcon />
};
